name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  # Usando o Personal Access Token gerado

      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: iguin777
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Gerar o conteúdo para o GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.2.0  # Verifique se está na versão mais recente
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Usando o token pessoal gerado
